#!/usr/bin/env bash

run_tests=''

if [[ -z ${@} ]]; then
    run_tests=$(ls -1 ./tests/??-*);
fi

for num in ${@}; do 
    test_name=$(printf "%02d" "${num}")
    test_file=$(ls -1 ./tests/${test_name}-*)
    run_tests="${run_tests}${test_file}"$'\n'
done

points=0
total_points=0
echo "Running Tests:"
for test in ${run_tests}; do
    test_file_name=$(basename "${test}")
    test_num="${test_file_name%%-*}"
    test_pts="${test_file_name##*-}"
    test_pts="${test_pts/.sh/}"
    test_name="${test_file_name%-*}"
    test_name="${test_name##*-}"
    printf " * %s %-20s [%s pts]\n" "${test_num}" "${test_name}" "${test_pts}"
    # run it
    (( total_points += test_pts ))
done
echo "Execution complete. [${points}/${total_points} pts]"
